# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_incubator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.CharField(default=0, max_length=20)),
                ('student_name', models.CharField(default='Nitin', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='coding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='question',
            name='single_valued',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='test_case',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_incubator.Question'),
        ),
    ]
